name: agroconnect
description: AgroConnect - Your Agricultural Marketplace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.4.9  # Updated to compatible version
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  http: ^1.1.0
  intl: ^0.18.1
  uuid: ^4.2.1
  shimmer: ^3.0.0
  # carousel_slider: ^4.2.1
  badges: ^3.1.2
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/